################################### Default Configuration ############################
baseurl = "https://wxfastmachinery.com/"
title = "Fastbest"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/fonts/DroidSerif.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
# [[params.plugins.css]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Category"
url = "category"
weight = 2

[[menu.main]]
name = "Concrete Cutter"
url = "concrete_cutter"
weight = 1
parent = "Category"

[[menu.main]]
name = "Plate Compactor"
url = "plate_compactor"
weight = 2
parent = "Category"

[[menu.main]]
name = "Tamping Rammer"
url = "tamping_rammer"
weight = 3
parent = "Category"

[[menu.main]]
name = "Power Trowel"
url = "power_trowel"
weight = 4
parent = "Category"

[[menu.main]]
name = "Surface Finishing Screed"
url = "surface_finishing_screed"
weight = 5
parent = "Category"

[[menu.main]]
name = "Grooving Machine"
url = "grooving_machine"
weight = 6
parent = "Category"

[[menu.main]]
name = "Concrete Vibrator"
url = "concrete_vibrator"
weight = 7
parent = "Category"

[[menu.main]]
name = "Vibrator Rollor"
url = "vibrator_rollor"
weight = 8
parent = "Category"

# [[menu.main]]
# name = "Products"
# url = "products"
# weight = 2

[[menu.main]]
name = "FAQ"
url = "faq"
weight = 3

# [[menu.main]]
# name = "Review"
# pre = "#"
# url = "testimonial"
# weight = 4

[[menu.main]]
name = "Contact"
url = "contact"
weight = 5

# footer menu
[[menu.footer]]
name = "FAQ"
url = "faq"
weight = 1

[[menu.footer]]
name = "Products"
url = "products"
weight = 2

# [[menu.footer]]
# name = "Terms & Conditions"
# url = "terms-conditions"
# weight = 3

[[menu.footer]]
name = "Contact"
url = "contact"
weight = 4


########################### Default parameters ##########################
[params]
logo = "images/logo.jpg"
logo2 = "images/logo.png"
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# currency
currency = "$"
# contact form action
contact_form_action = "https://formspree.io/f/moqrajbg" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Snipcart
[params.snipcart]
enable = false
# snipcart public api key
# snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Developed By Wuxi Fast Machinery Technology Co., Ltd."

################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Developed By Wuxi Fast Machinery Technology Co., Ltd."